# Generated by Django 6.0.3 on 2026-03-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_detallecotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
